# Conda environment definition for a unified PyTorch and TensorFlow environment
name: ml-unified-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # --- Core Frameworks and CUDA ---
  # Let Conda handle the installation of the big frameworks and the CUDA toolkit
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow-gpu  # This is the conda package for GPU-enabled TensorFlow
  - pytorch-cuda=12.1 # Pin the CUDA version for consistency

  # --- Other Core Libraries from Conda ---
  # Install as much as possible with Conda for maximum stability
  - pip
  - pyqt
  - gxx_linux-64  # For Linux, same as before
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - h5py
  - dask
  - mlflow
  - biopython
  - networkx
  - gensim
  - transformers

  # --- Pip-specific packages ---
  # For packages not on Conda or that have special requirements
  - pip:
    - python-louvain
    - torch-geometric-signed-directed