# Conda environment definition for a unified PyTorch and TensorFlow environment
name: ml-unified-env

channels:
  - nvidia # Added nvidia channel with the highest priority for CUDA libraries
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # --- Core Frameworks and CUDA ---
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow-gpu
  - pytorch-cuda=12.1

  # --- Other Core Libraries from Conda ---
  - pip
  - pyqt
  - gxx_linux-64
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - h5py
  - dask
  - mlflow
  - biopython
  - networkx
  - gensim
  - transformers

  # --- Pip-specific packages ---
  - pip:
    - python-louvain
    - torch-geometric-signed-directed